version: '3.9'

services:
  db:
    image: postgres
    environment:
      - 'POSTGRES_HOST_AUTH_METHOD=trust'

  web:
    build: .
    command: gunicorn blogAPI.wsgi:application --b 0.0.0.0:8002 --workers 4
    volumes:
      - .:/code
    ports:
      - '8002:8002'
    depends_on:
      - db
